version: 1
services:
  - type: web
    name: task-management-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
